site_name: PLUS ERP
site_description: ERP Programmer's Manual
site_author: Martinez Ortiz Eduardo Antonio
site_url: https://github.com/EduardoMartinez68/MANUAL_ERP_PLUS

theme:
  name: material
  language: en
  logo: assets/logo_white.png     
  favicon: assets/favicon.ico  

  palette:
    # mode white
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # mode black
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EduardoMartinez68
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Apps: 
    - Create an App: backend.md
    - Create a Plugin: backend.md
  - PLUS Bussiness > Backend: backend.md
  - PLUS UI > Frontend:
      - Introduction: frontend.md
      - Modular Logic:
          - variables: module/variables.md
          - functions: module/functions.md
      - Inputs:
          - PlusTitle: inputs/plus-title.md
          - InputField: inputs/input-field.md
          - PlusQuantity: inputs/plus-quantity.md
          - EditQuantity: inputs/edit-quantity.md
          - PlusSelect: inputs/PlusSelect.md
          - PlusMultiSelect: inputs/PlusMultiSelect.md
          - PlusCountry: inputs/PlusCountry.md
          - PlusSwitch: inputs/PlusSwitch.md
      - Dynamic:
          - search-bar: dynamic/search-bar.md
      - Componentes:
          - InfoLabel: components/info-label.md
          - MessagePop: components/message-pop.md
          - PlusPanel: components/plus-panel.md
          - PlusNavbar: components/plus-navbar.md
          - ConfirmButton: components/confirm-button.md
          - ConfirmDialog: components/confirm-dialog.md
          - AppMenu: components/AppMenu.md
          - KeyBind: components/KeyBind.md
          - PlusHelp: components/PlusHelp.md
          - CreateHelp: components/CreateHelp.md
          - PlusSelectDate: components/PlusSelectDate.md
          - PlusTabs: components/PlusTabs.md
          - PlusActions: components/PlusActions.md
      - Functions:
          - nextWeb: functions/nextWeb.md
          - get_text_and_keys: functions/get_text_and_keys.md
          - show_message_question: functions/show_message_question.md
          - set_value_plus_select: functions/set_value_plus_select.md
          - set_value_plus_select_multiple: functions/set_value_plus_select_multiple.md
          - get_value_plus_select: functions/get_value_plus_select.md
          - plus_delete_with_help_button: functions/plus_delete_with_help_button.md
          - get_status_plus_switch: functions/get_status_plus_switch.md
          - set_status_plus_switch: functions/set_status_plus_switch.md
          - update_container_with_seeker: functions/update_container_with_seeker.md
      - Currency:
            - get_currency_system: currency/get_currency_system.md
            - format_currency: currency/format_currency.md
      - Time:
            - format_date_to_text: time/format_date_to_text.md
            - format_date: time/format_date.md
  - API: api.md